/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huawei_kunpengimsystem_utils_NativeUtil */

#ifndef _Included_com_huawei_kunpengimsystem_utils_NativeUtil
#define _Included_com_huawei_kunpengimsystem_utils_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huawei_kunpengimsystem_utils_NativeUtil
 * Method:    getSha256Digest
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_huawei_kunpengimsystem_utils_NativeUtil_getSha256Digest
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_huawei_kunpengimsystem_utils_NativeUtil
 * Method:    getCrc32Digest
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_huawei_kunpengimsystem_utils_NativeUtil_getCrc32Digest
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_huawei_kunpengimsystem_utils_NativeUtil
 * Method:    getTimeMs
 * Signature: (Ljava/lang;)Ljava/lang;
 */
JNIEXPORT jstring JNICALL Java_com_huawei_kunpengimsystem_utils_NativeUtil_getCpuClocks
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
